// Curated restaurant candidates. No synthetic ratings, current opening hours, or invented prices.
window.TRAVEL_RESTAURANTS=[
  {city:'北京',name:'方砖厂69号炸酱面（方砖厂胡同）',dish:'炸酱面',area:'东城区方砖厂胡同',budget:'¥',fit:'京味面食、单人用餐',reason:'地方特色明确，米其林指南当前列为必比登推介；面食价格档相对容易控制。',caution:'热门时段可能排队；点单前核对营业与实际售价。',source:'米其林指南 · 当前餐厅名录',url:'https://guide.michelin.com/ph/en/beijing-municipality/beijing/restaurants/bib-gourmand'},
  {city:'北京',name:'爆肚金生隆（东城）',dish:'爆肚、涮肉',area:'东城区和平里东街13号',budget:'¥¥',fit:'想试京味内脏与铜锅',reason:'米其林指南列出特色爆肚与涮肉，并注明了迁址后的店铺地址。',caution:'不吃内脏者先看菜单；店址曾变更，出发前核对。',source:'米其林指南 · 店铺页面',url:'https://guide.michelin.com/us/en/beijing-municipality/beijing/restaurant/bao-du-jin-sheng-long'},
  {city:'北京',name:'美·大董（南新仓）',dish:'北京烤鸭',area:'东城区东四十条甲22号南新仓商务大厦1—2层',budget:'¥¥¥',fit:'烤鸭正餐、多人聚餐',reason:'米其林指南收录烤鸭特色与明确地址；与平价面食形成预算和场景对照。',caution:'价格档较高，建议先看菜单、份量与预约要求。',source:'米其林指南 · 店铺页面',url:'https://guide.michelin.com/en/beijing-municipality/beijing/restaurant/gastro-esthetics-dadong'},
  {city:'成都',name:'甘记肥肠粉',dish:'肥肠粉、锅盔',area:'金牛区马鞍北路18号附1—3号',budget:'¥',fit:'快餐小吃、喜欢内脏',reason:'米其林指南收录；可选择麻辣汤或白汤，适合按口味调整。',caution:'不吃内脏者不宜为排队勉强尝试，先确认现场营业。',source:'米其林指南 · 店铺页面',url:'https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/gan-ji-fei-chang-fen'},
  {city:'成都',name:'永乐饭店（武侯）',dish:'家常川菜',area:'武侯区肖家河中街36号',budget:'¥',fit:'多人分菜、想吃家常川菜',reason:'米其林指南收录传统川菜，也提到非辣菜选择，适合同行口味不同的人。',caution:'资料提示可能排队，先确认当天等位和菜价。',source:'米其林指南 · 店铺页面',url:'https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/yongle-restaurant-wuhou'},
  {city:'成都',name:'锦城印象（武侯祠大街）',dish:'川味火锅',area:'武侯区武侯祠大街19号附94号',budget:'¥¥',fit:'多人火锅、武侯祠附近',reason:'米其林指南收录，地点适合与武侯祠一带安排在同一城区行程。',caution:'牛油红锅较辣；核对锅底、蘸料与服务项目收费。',source:'米其林指南 · 店铺页面',url:'https://guide.michelin.com/sg/zh_CN/chengdu-municipality/chengdu/restaurant/china-samite-hot-pot-wuhouci-street'},
  {city:'西安',name:'同盛祥（钟楼店）',dish:'牛羊肉泡馍',area:'钟楼附近 · 具体门牌请以地图核对',budget:'现场核价',fit:'第一次体验泡馍、钟楼步行线',reason:'陕西档案资料记录其泡馍技艺与品牌历史，西安饮食年度报告列出同盛祥非遗制作技艺。',caution:'资料证明品牌与技艺，不等于当前好评或当天营业；核对分店和菜单。',source:'陕西档案信息网 · 品牌资料',url:'https://daj.shaanxi.gov.cn/Article/View?id=2669'},
  {city:'西安',name:'德发长（钟楼店）',dish:'饺子',area:'钟楼附近 · 具体门牌请以地图核对',budget:'现场核价',fit:'饺子口味、多人分享',reason:'西安饮食年度报告列出德发长饺子制作技艺，作为和泡馍不同的陕味候选。',caution:'套餐与单点价可能差很多，点单前看清菜品和份量。',source:'西安饮食 · 2024年度报告',url:'https://pdf.dfcfw.com/pdf/H2_AN202504181658566956_1.pdf'},
  {city:'西安',name:'老孙家饭庄',dish:'牛羊肉泡馍',area:'西安市区 · 请确认具体分店',budget:'现场核价',fit:'想对比不同泡馍做法',reason:'西安饮食年度报告列出老孙家泡馍制作技艺；可与同盛祥按汤底、肉量和价格比较。',caution:'同品牌可能有不同分店，地图搜索后核对招牌与营业。',source:'西安饮食 · 2024年度报告',url:'https://pdf.dfcfw.com/pdf/H2_AN202504181658566956_1.pdf'},
  {city:'长白山',name:'百铺乐核桃烤串',dish:'特色烤串',area:'池北区二道白河镇 · 以地图定位为准',budget:'现场核价',fit:'登山后吃烤串、多人分享',reason:'长白山管委会规划中期评估报告将其列为当地餐饮名店，具有区域辨识度。',caution:'来源较早，不代表当前仍营业；先查地图与菜单。',source:'长白山管委会 · 规划中期评估',url:'https://changbaishan.gov.cn/shjj/qhgh/cbs145gh/202401/P020240201510754367725.pdf'},
  {city:'长白山',name:'万巷食府融合餐厅',dish:'融合菜',area:'池北区二道白河镇 · 以地图定位为准',budget:'现场核价',fit:'同行口味不同、想吃正餐',reason:'同一官方评估报告列为当地餐饮名店，与烤串和朝鲜族风味形成不同选择。',caution:'来源较早；店址、营业状态和菜单需再次核对。',source:'长白山管委会 · 规划中期评估',url:'https://changbaishan.gov.cn/shjj/qhgh/cbs145gh/202401/P020240201510754367725.pdf'},
  {city:'长白山',name:'北朝餐厅',dish:'朝鲜族风味',area:'池北区二道白河镇 · 以地图定位为准',budget:'现场核价',fit:'想尝当地朝鲜族风味',reason:'长白山管委会资料将其列入当地特色餐饮名单，补足区域饮食风格。',caution:'来源较早；先查近期营业、菜单和食材适配，不按旧推荐盲目前往。',source:'长白山管委会 · 规划中期评估',url:'https://changbaishan.gov.cn/shjj/qhgh/cbs145gh/202401/P020240201510754367725.pdf'}
];

